<?php

namespace Database\Seeders;

use App\Models\Nutrient;
use Illuminate\Database\Seeder;

class NutrientSeeder extends Seeder
{
    public function run(): void
    {
        $nutrients = [
            ['legacy_id' => 1, 'name' => 'Total Fat'],
            ['legacy_id' => 2, 'name' => 'Saturated Fat'],
            ['legacy_id' => 3, 'name' => 'Polyunsaturated Fat'],
            ['legacy_id' => 4, 'name' => 'Monounsaturated Fat'],
            ['legacy_id' => 5, 'name' => 'Cholesterol'],
            ['legacy_id' => 6, 'name' => 'Sodium'],
            ['legacy_id' => 7, 'name' => 'Potassium'],
            ['legacy_id' => 8, 'name' => 'Total Carbohydrate'],
            ['legacy_id' => 9, 'name' => 'Dietary Fiber'],
            ['legacy_id' => 10, 'name' => 'Sugars'],
            ['legacy_id' => 15, 'name' => 'Protein'],
            ['legacy_id' => 12, 'name' => 'Vitamin C'],
            ['legacy_id' => 13, 'name' => 'Calcium'],
            ['legacy_id' => 14, 'name' => 'Iron'],
            ['legacy_id' => 11, 'name' => 'Vitamin A'],
            ['legacy_id' => 16, 'name' => 'B17 (Amygdalin)'],
            ['legacy_id' => 17, 'name' => 'Lipids'],
            ['legacy_id' => 18, 'name' => 'AHCC'],
            ['legacy_id' => 19, 'name' => 'Trans Fat'],
            ['legacy_id' => 20, 'name' => 'Transport C PLUS'],
            ['legacy_id' => 21, 'name' => 'Alpha Lipoic Acid'],
            ['legacy_id' => 22, 'name' => 'Citrus Bioflavanoid Complex'],
            ['legacy_id' => 23, 'name' => 'Acerola Powder'],
            ['legacy_id' => 24, 'name' => 'Rose Hips Powder'],
            ['legacy_id' => 25, 'name' => 'Rutin Powder'],
            ['legacy_id' => 26, 'name' => 'Vitamin B6'],
            ['legacy_id' => 27, 'name' => 'Blend of Peptide Bound Amino Acid Sources'],
            ['legacy_id' => 28, 'name' => 'L-Histidine'],
            ['legacy_id' => 29, 'name' => 'L-Isoleucine'],
            ['legacy_id' => 30, 'name' => 'L-Leucine'],
            ['legacy_id' => 31, 'name' => 'L-Lysine'],
            ['legacy_id' => 32, 'name' => 'L-Methionine'],
            ['legacy_id' => 33, 'name' => 'L-Phenylalanine'],
            ['legacy_id' => 34, 'name' => 'L-Threonine'],
            ['legacy_id' => 35, 'name' => 'L-Tryptophan'],
            ['legacy_id' => 36, 'name' => 'L-Valine'],
            ['legacy_id' => 37, 'name' => 'L-Alanine'],
            ['legacy_id' => 38, 'name' => 'L-Arginine'],
            ['legacy_id' => 39, 'name' => 'L-Aspartic Acid'],
            ['legacy_id' => 40, 'name' => 'L-Cysteine'],
            ['legacy_id' => 41, 'name' => 'L-Glutamic Acid'],
            ['legacy_id' => 42, 'name' => 'L-Glutamine'],
            ['legacy_id' => 43, 'name' => 'Glycine'],
            ['legacy_id' => 44, 'name' => 'L-Hydroxyproline'],
            ['legacy_id' => 45, 'name' => 'L-Ornithine'],
            ['legacy_id' => 46, 'name' => 'L-Proline'],
            ['legacy_id' => 47, 'name' => 'L-Serine'],
            ['legacy_id' => 48, 'name' => 'L-Tyrosine'],
            ['legacy_id' => 49, 'name' => 'Zanthin Natural Astaxanthin'],
            ['legacy_id' => 50, 'name' => 'Beta 1,3/1,6 D-Glucan Powder'],
            ['legacy_id' => 51, 'name' => 'Maitake Mushroom Powder'],
            ['legacy_id' => 52, 'name' => 'Vitamin D'],
            ['legacy_id' => 53, 'name' => 'Vitamin K'],
            ['legacy_id' => 54, 'name' => 'Vitamin K-2'],
            ['legacy_id' => 55, 'name' => 'Vitamin D-3'],
            ['legacy_id' => 56, 'name' => 'Thiamin'],
            ['legacy_id' => 57, 'name' => 'Phosphorous'],
            ['legacy_id' => 58, 'name' => 'Magnesium'],
            ['legacy_id' => 59, 'name' => 'Zinc'],
            ['legacy_id' => 60, 'name' => 'Copper'],
            ['legacy_id' => 61, 'name' => 'Manganese'],
            ['legacy_id' => 62, 'name' => 'Horsetail Herb'],
            ['legacy_id' => 63, 'name' => 'Boron'],
            ['legacy_id' => 64, 'name' => 'Ginkgo Extract'],
            ['legacy_id' => 65, 'name' => 'RoseOx'],
            ['legacy_id' => 66, 'name' => 'Phosphatidyl Serine'],
            ['legacy_id' => 67, 'name' => 'Huperzine Complex'],
            ['legacy_id' => 68, 'name' => 'Gotu Kola'],
            ['legacy_id' => 69, 'name' => 'Choline'],
            ['legacy_id' => 70, 'name' => 'S-Adenosyl-Methionine (SAM-e)'],
            ['legacy_id' => 71, 'name' => 'Cellfood Proprietary Blend'],
            ['legacy_id' => 72, 'name' => 'Garcinia Cambogia Extract'],
            ['legacy_id' => 73, 'name' => 'L-Carnitine'],
            ['legacy_id' => 74, 'name' => 'Silver'],
            ['legacy_id' => 75, 'name' => 'Vitamin E'],
            ['legacy_id' => 76, 'name' => 'Coenzyme Q10'],
            ['legacy_id' => 77, 'name' => 'Tumeric Root Extract'],
            ['legacy_id' => 78, 'name' => 'Proprietary Blend'],
            ['legacy_id' => 79, 'name' => 'Esiak Tea Concentrate'],
            ['legacy_id' => 80, 'name' => 'Proprietary Blend'],
            ['legacy_id' => 81, 'name' => 'Organic Flax Seed Oil'],
            ['legacy_id' => 82, 'name' => 'Unique Blend of'],
            ['legacy_id' => 83, 'name' => 'Superoxide Dimutase /Gliadin Complex (GliSODin) (250 IU)'],
            ['legacy_id' => 84, 'name' => 'Graviola'],
            ['legacy_id' => 85, 'name' => 'Organic Mushroom Blend'],
            ['legacy_id' => 86, 'name' => 'Astragalus Root Extract'],
            ['legacy_id' => 87, 'name' => 'Calcium Magnesium Inositol Hexaphosphate'],
            ['legacy_id' => 88, 'name' => 'Yielding: IP 6'],
            ['legacy_id' => 89, 'name' => 'Glucosamine HCI'],
            ['legacy_id' => 90, 'name' => 'Boswellin'],
            ['legacy_id' => 91, 'name' => 'Sea Cucumber'],
            ['legacy_id' => 92, 'name' => 'Bromelain'],
            ['legacy_id' => 93, 'name' => 'PABA'],
            ['legacy_id' => 94, 'name' => 'Alfalfa Juice Concentrate'],
            ['legacy_id' => 95, 'name' => 'Pantothenic Acid'],
            ['legacy_id' => 96, 'name' => 'Niacin'],
            ['legacy_id' => 97, 'name' => 'Magnesium'],
            ['legacy_id' => 98, 'name' => 'Xylitol'],
            ['legacy_id' => 99, 'name' => 'Vitamin A (40% as Beta-Carotene)'],
            ['legacy_id' => 100, 'name' => 'Vitamin C (as Ascorbic Acid)'],
            ['legacy_id' => 101, 'name' => 'Vitamin D (as Ergocalciferol)'],
            ['legacy_id' => 102, 'name' => 'Vitamin E (from d-alpha Tocopheryl Acetate)'],
            ['legacy_id' => 103, 'name' => 'Thiamin (Vitamin B-1) (from Thiamine Hydrochloride)'],
            ['legacy_id' => 104, 'name' => 'Riboflavin (Vitamin B-2)'],
            ['legacy_id' => 105, 'name' => 'Vitamin B-6 (from Pyridoxine Hydrochloride)'],
            ['legacy_id' => 106, 'name' => 'Folate (as Folic Acid)'],
            ['legacy_id' => 107, 'name' => 'Vitamin B-12 (as Cyanocobalamin)'],
            ['legacy_id' => 108, 'name' => 'Pantothenic Acid (Vitamin B-5) (from Calcium d-Pantothenate)'],
            ['legacy_id' => 109, 'name' => 'Calcium (from Calcium Carbonate)'],
            ['legacy_id' => 110, 'name' => 'Iodine [from Kelp (Laminaria digitata)]'],
            ['legacy_id' => 111, 'name' => 'Biotin'],
            ['legacy_id' => 112, 'name' => 'Zinc (from Zinc AAC)'],
            ['legacy_id' => 113, 'name' => 'Selenium (from Selenopure L-Selenomethionine)'],
            ['legacy_id' => 114, 'name' => 'Manganese (from Manganese AAC)'],
            ['legacy_id' => 115, 'name' => 'Chromium (from Chromium Chelavite AAC)'],
            ['legacy_id' => 116, 'name' => 'Potassium (from Potassium Chloride)'],
            ['legacy_id' => 117, 'name' => 'Orange Juice Powder'],
            ['legacy_id' => 118, 'name' => 'VitaBerry Hi-ORAC Fruit Blend'],
            ['legacy_id' => 119, 'name' => 'Aloe Vera Juice'],
            ['legacy_id' => 120, 'name' => 'Colloidal Minerals (Fulvic Acid)'],
            ['legacy_id' => 121, 'name' => 'Rice Protein Concentrate (from Non-GMO Brown Rice)'],
            ['legacy_id' => 122, 'name' => 'Choline (from Choline Bitartrate)'],
            ['legacy_id' => 123, 'name' => 'Inositol'],
            ['legacy_id' => 124, 'name' => 'Grape Seed Extract (Vitis vinifera) (Standardized for Polyphenois)'],
            ['legacy_id' => 125, 'name' => 'Citrus Bioflavonoids'],
            ['legacy_id' => 126, 'name' => 'Lutein (FloraGLO) (from Marigold Extract)'],
            ['legacy_id' => 127, 'name' => 'Lycopene (from Natural Tomato Extract)'],
            ['legacy_id' => 128, 'name' => 'Vitamin C (from Ascorbyl Palmitate)'],
            ['legacy_id' => 129, 'name' => 'Milk Thistle (Standardized Extract) (Seeds) (Silybum marianum)'],
            ['legacy_id' => 130, 'name' => 'Proprietary herbal-Nutrient Blend'],
            ['legacy_id' => 131, 'name' => 'L-Glutathione (Free-Form) (Reduced)'],
            ['legacy_id' => 132, 'name' => 'N-Acetyl Cysteine (NAC)'],
            ['legacy_id' => 133, 'name' => 'Bupleurum (4:1 Conc. Extract) (Root) (Bupleurum chinense)'],
            ['legacy_id' => 134, 'name' => 'Grape Seed (Standardized Extract) (Vitis vinefera)'],
            ['legacy_id' => 135, 'name' => 'Dandelion (4:1 Conc. Extract) (Root) (Taraxacum officinale)'],
            ['legacy_id' => 136, 'name' => 'L-Carnitine Base'],
            ['legacy_id' => 137, 'name' => 'Scute (4:1 Conc. Extract) (Root) (Sculellariae baicalensis)'],
            ['legacy_id' => 138, 'name' => 'Pueraria (4:1 Conc. Extract) (Flower) (Pueraria thunbergiana)'],
            ['legacy_id' => 139, 'name' => 'Schisandra (Fruit) (Schisandra chinensis)'],
            ['legacy_id' => 140, 'name' => 'Barberry (Root Bark) (Berberis vulgaris)'],
            ['legacy_id' => 141, 'name' => 'Turmeric (Root) (Curcuma longa)'],
            ['legacy_id' => 142, 'name' => 'Greater Celandine (4:1 Conc. Extract) (Whole Plant)'],
            ['legacy_id' => 143, 'name' => 'Zinc (As Gluconate)'],
            ['legacy_id' => 144, 'name' => 'Pancreatin 10X'],
            ['legacy_id' => 145, 'name' => 'Papain'],
            ['legacy_id' => 146, 'name' => 'Bromelain'],
            ['legacy_id' => 147, 'name' => 'Amylase'],
            ['legacy_id' => 148, 'name' => 'Lipase'],
            ['legacy_id' => 149, 'name' => 'Trypsin'],
            ['legacy_id' => 150, 'name' => 'a-Chymotrypsin'],
            ['legacy_id' => 151, 'name' => 'Super Oxide Dismutase (SOD)'],
            ['legacy_id' => 152, 'name' => 'Catalase'],
            ['legacy_id' => 153, 'name' => 'Rutin'],
            ['legacy_id' => 154, 'name' => 'Thymus Substance'],
            ['legacy_id' => 155, 'name' => 'Serrazimes'],
            ['legacy_id' => 156, 'name' => 'Nattozimes'],
            ['legacy_id' => 157, 'name' => 'L-Glutathione'],
            ['legacy_id' => 158, 'name' => 'Folic Acid'],
            ['legacy_id' => 159, 'name' => 'Iodine'],
            ['legacy_id' => 160, 'name' => 'Selenium'],
            ['legacy_id' => 161, 'name' => 'Copper (as Copper Gluconate)'],
            ['legacy_id' => 162, 'name' => 'Manganese (as Manganese Gluconate)'],
            ['legacy_id' => 163, 'name' => 'Chromium (as Chromium Picolinate)'],
            ['legacy_id' => 164, 'name' => 'Potassium (as Potassium Citrate)'],
            ['legacy_id' => 165, 'name' => 'Boron (as Boron Citrate)'],
            ['legacy_id' => 166, 'name' => 'Methionine'],
            ['legacy_id' => 167, 'name' => 'Hesperidin (Citrus sinensis) (fruit)'],
            ['legacy_id' => 168, 'name' => 'Betaine Hydrochloride'],
            ['legacy_id' => 169, 'name' => 'Eleuthero Root (Eleutherococcus senticosus)'],
            ['legacy_id' => 170, 'name' => 'L-Taurine'],
            ['legacy_id' => 171, 'name' => 'Probiotic Complex (L-Acidophilus, L-Bulgaricus and B-Bifidum)'],
            ['legacy_id' => 172, 'name' => 'Bee Pollen'],
            ['legacy_id' => 173, 'name' => 'Spirulina/Chlorella (Chlorophyllins)'],
            ['legacy_id' => 174, 'name' => 'Bee Propolis'],
            ['legacy_id' => 175, 'name' => 'Wheat Grass/Barley Grass (Chlorophyllins)'],
            ['legacy_id' => 176, 'name' => 'L-Glutathionine'],
            ['legacy_id' => 177, 'name' => 'Fish Oil and Borrage Oil (containing Omega-3 and Omega-6 Lipids)'],
            ['legacy_id' => 178, 'name' => 'Royal Jelly'],
            ['legacy_id' => 179, 'name' => 'Licorice Extract (Glycyrrhizin) (root)'],
            ['legacy_id' => 180, 'name' => 'Bilberry Extract (Anthocyanins)(fruit)'],
            ['legacy_id' => 181, 'name' => 'Pycnogenol (Maritime Pine Bark Extract)'],
            ['legacy_id' => 182, 'name' => 'Echinacea/Goldenseal (Echinacosides) (root)'],
            ['legacy_id' => 183, 'name' => 'Garlic (bulb)'],
            ['legacy_id' => 184, 'name' => 'Polyphenol Complex (Red Wine Extract, Green Tea Extract (Camellia sinensis) (leaf)'],
            ['legacy_id' => 185, 'name' => 'Vegetable Complex (from Beets, Yams, Celery, Brussels Sprouts, Carrots, Cauliflower, Broccoli)'],
            ['legacy_id' => 186, 'name' => 'Citrus Complex (from Lemon, Orange, Lime, Grapefruit)'],
            ['legacy_id' => 187, 'name' => 'Mushroom Complex (from Maitake, Reishi, Shitake)'],
            ['legacy_id' => 188, 'name' => 'Vitamin Co-Factor Complex'],
            ['legacy_id' => 189, 'name' => 'Lycopene'],
            ['legacy_id' => 190, 'name' => 'Lutein (purified from Extracted Marigolds)'],
            ['legacy_id' => 191, 'name' => 'Alpha Lipoic Acid'],
            ['legacy_id' => 192, 'name' => 'Tocotrienols'],
            ['legacy_id' => 193, 'name' => "Men's Bioactive Complex"],
            ['legacy_id' => 194, 'name' => 'Thiamin (Vitamin B1) (as Thiamine Mononitrate)'],
            ['legacy_id' => 195, 'name' => 'Boron Complex (as Boron Aspartate, Boron Citrate and Boron Ascorbate)'],
            ['legacy_id' => 196, 'name' => 'Probiotic Complex'],
            ['legacy_id' => 197, 'name' => "Women's Bioactive Complex"],
            ['legacy_id' => 198, 'name' => 'Potassium'],
            ['legacy_id' => 199, 'name' => 'Magnesium'],
            ['legacy_id' => 200, 'name' => 'MSM (Methylsulphonylmethane)'],
            ['legacy_id' => 201, 'name' => 'Evening Primrose Oil (cold pressed) (Oenothera biennis) (seed)'],
            ['legacy_id' => 202, 'name' => 'Canola Oil (cold pressed)'],
            ['legacy_id' => 203, 'name' => 'Black Currant Oil (Ribes nigrum) (seed)'],
            ['legacy_id' => 204, 'name' => 'Pumpkin Seed Oil (Cucurbita pepo) (seed)'],
            ['legacy_id' => 205, 'name' => 'Vitamin B12 (as Methylcobalamin)'],
            ['legacy_id' => 206, 'name' => 'Iodine (from Potassium Iodide)'],
            ['legacy_id' => 207, 'name' => 'Copper'],
            ['legacy_id' => 208, 'name' => 'Manganese'],
            ['legacy_id' => 209, 'name' => 'Molybdenum'],
            ['legacy_id' => 210, 'name' => 'Fish Oil Concentrate'],
            ['legacy_id' => 211, 'name' => 'DHA (Docosahexaenoic Acid)'],
            ['legacy_id' => 212, 'name' => 'EPA (Eicosapentaenoic Acid)'],
            ['legacy_id' => 213, 'name' => 'Borage Oil (seed)'],
            ['legacy_id' => 214, 'name' => 'GLA (Gamma Linolenic Acid)'],
            ['legacy_id' => 215, 'name' => 'Lutein (from Marigold Flowers)'],
            ['legacy_id' => 216, 'name' => 'Green Tea extract (Camellia sinenis) (40% catechins)'],
            ['legacy_id' => 217, 'name' => 'Milk Thistle extract (Silybum marianum) (80% Silymarin)'],
            ['legacy_id' => 218, 'name' => 'Curcumin extract (Curcuma longa) (min. 90% extract)'],
            ['legacy_id' => 219, 'name' => 'Quercetin'],
            ['legacy_id' => 220, 'name' => 'Bromelain (from pineapple) (2000 GDU)'],
            ['legacy_id' => 221, 'name' => 'Cranberry Powder extract'],
            ['legacy_id' => 222, 'name' => 'Rosemary extract (Rosmarinus officinalis)'],
            ['legacy_id' => 223, 'name' => 'Grapeseed extract (90% polyphenols)'],
            ['legacy_id' => 224, 'name' => 'Ginkgo Biloba extract (24% ginkgoflavonglycosides)'],
            ['legacy_id' => 225, 'name' => 'Ginger Root (Zingiber officinalis)'],
            ['legacy_id' => 226, 'name' => 'Hawthorn Berry extract (Crataegus oxyacantha)'],
            ['legacy_id' => 227, 'name' => 'Bilberry standardized extract (Vaccinium mytillus)'],
            ['legacy_id' => 228, 'name' => 'Vitamin B12'],
            ['legacy_id' => 229, 'name' => 'Synergized Algae'],
            ['legacy_id' => 230, 'name' => 'Synergized Photonutrients and Enzymes'],
            ['legacy_id' => 231, 'name' => 'Synergized Tonic Herbal Extracts and Asian Mushrooms'],
            ['legacy_id' => 232, 'name' => 'Synergized Green Juices'],
            ['legacy_id' => 233, 'name' => 'Synergized Western Herbs'],
            ['legacy_id' => 234, 'name' => 'Synergized Natural Antioxidants'],
            ['legacy_id' => 235, 'name' => 'Polygonum cuspidatum Extract (Rhizome) (50% Natural Trans-Resveratrol - 200 mg)'],
            ['legacy_id' => 236, 'name' => 'Red Wine Extract (Alcohol-Free) (Vitis vinifera) (Fruit) (Standardized for Polyphenols)'],
            ['legacy_id' => 237, 'name' => 'Selenium (as L-Selenomethionine)'],
            ['legacy_id' => 238, 'name' => 'Organic Spirulina'],
            ['legacy_id' => 239, 'name' => 'Chlorophyll'],
            ['legacy_id' => 240, 'name' => 'Niacin (as Inositol Nicotinate)'],
            ['legacy_id' => 241, 'name' => 'Calcium (as tri-calcium Phosphate and calcium Gluconate)'],
            ['legacy_id' => 242, 'name' => 'Inositol'],
            ['legacy_id' => 243, 'name' => 'Dymethyglycine'],
            ['legacy_id' => 244, 'name' => 'Trimethylglycine (Betaine HCL)'],
            ['legacy_id' => 245, 'name' => 'Bovine Colostrum'],
            ['legacy_id' => 246, 'name' => 'Larch Arabinogalactan (ImmuneEnhancer)'],
            ['legacy_id' => 247, 'name' => 'Olive Leaf (Olea europaeaI) Standardized Extract (min. 6% Oleuropeins)'],
            ['legacy_id' => 248, 'name' => 'Astragalus (Astragalus membranaceus) (Root)'],
            ['legacy_id' => 249, 'name' => 'Iodine (from Kelp and Irish Moss)'],
            ['legacy_id' => 250, 'name' => 'Zinc (from L-Optizinc- Zinc L-Methionine Complex)'],
            ['legacy_id' => 251, 'name' => 'Selenuium (from L-Selenomethionine) (Yeast-Free)'],
            ['legacy_id' => 252, 'name' => 'L-Tyrosine (Free-Form)'],
            ['legacy_id' => 253, 'name' => 'Irish Moss (Chondius Crispus) (Thallus)'],
            ['legacy_id' => 254, 'name' => 'Guggul (Commiphora Mukul) (Resinous Sap)'],
            ['legacy_id' => 255, 'name' => 'Kelp (laminaria digitate) (Whole Plant)'],
            ['legacy_id' => 256, 'name' => 'Ashwagandha (Witharia Sommifera) (Root)'],
            ['legacy_id' => 257, 'name' => 'ConcentraceTrace Minerals'],
            ['legacy_id' => 258, 'name' => 'Proprietary Multi-Enzyme Blend'],
            ['legacy_id' => 259, 'name' => 'Protease'],
            ['legacy_id' => 260, 'name' => 'Acid-Stable Protease'],
            ['legacy_id' => 261, 'name' => 'Amylase'],
            ['legacy_id' => 262, 'name' => 'Lipase'],
            ['legacy_id' => 263, 'name' => 'Cellulase'],
            ['legacy_id' => 264, 'name' => 'Lactase'],
            ['legacy_id' => 265, 'name' => 'Papain (from Papaya)'],
            ['legacy_id' => 266, 'name' => 'Bromelain (from Pineapple)'],
            ['legacy_id' => 267, 'name' => 'Emulsified Vitamin A'],
            ['legacy_id' => 268, 'name' => 'Vitamin E (as unesterified d-alpha Tocopherol)'],
            ['legacy_id' => 269, 'name' => 'Selenium (from Selenium Yeast)'],
            ['legacy_id' => 270, 'name' => 'Natural Mixed Tocopherols (d-beta, d-gamma, d-delta)'],
            ['legacy_id' => 271, 'name' => 'Lipids'],
            ['legacy_id' => 272, 'name' => 'BioCore Kids Vegetarian Enzymes'],
            ['legacy_id' => 273, 'name' => 'Amylase (from Aspergillus oryzae)'],
            ['legacy_id' => 274, 'name' => 'Protease (from Aspergillus oryzae)'],
            ['legacy_id' => 275, 'name' => 'Protease (from Aspergillus oryzae)'],
            ['legacy_id' => 276, 'name' => 'Lactase (from Aspergillus oryzae)'],
            ['legacy_id' => 277, 'name' => 'Glucoamylase (from Aspergillus niger)'],
            ['legacy_id' => 278, 'name' => 'Protease (from Aspergillus niger)'],
            ['legacy_id' => 279, 'name' => 'Diastase (from Aspergillus oryzae)'],
            ['legacy_id' => 280, 'name' => 'Protease (from Aspergillus oryzae)'],
            ['legacy_id' => 281, 'name' => 'Lipase (from Candida rugosa, Aspergillus niger, and Rhizopus oryzae)'],
            ['legacy_id' => 282, 'name' => 'Invertase (Saccharomyces cerevisiae)'],
            ['legacy_id' => 283, 'name' => 'Apricot Seed Extract, B17 (Amygdalin)'],
            ['legacy_id' => 284, 'name' => 'Bitter Apricot Seed Powder'],
            ['legacy_id' => 285, 'name' => 'Sugar Alcohols'],
            ['legacy_id' => 286, 'name' => 'Purified Silver'],
            ['legacy_id' => 287, 'name' => 'Aloe Vera Extract (200:1 concentrate)'],
            ['legacy_id' => 288, 'name' => 'Organic Aloe Vera'],
            ['legacy_id' => 289, 'name' => 'Purified Silver'],
            ['legacy_id' => 290, 'name' => 'Reishi Mycelia Biomass'],
            ['legacy_id' => 291, 'name' => 'Shiitake Mycelia Biomass'],
            ['legacy_id' => 292, 'name' => 'Maitake Mycelia Biomass'],
            ['legacy_id' => 293, 'name' => 'Turkey Tail Mycelia Biomass'],
            ['legacy_id' => 294, 'name' => 'Proprietary Blend'],
            ['legacy_id' => 295, 'name' => 'Vitamin A'],
            ['legacy_id' => 296, 'name' => 'Vitamin C'],
            ['legacy_id' => 297, 'name' => 'Vitamin D'],
            ['legacy_id' => 298, 'name' => 'Vitamin E'],
            ['legacy_id' => 299, 'name' => 'Thamin - Vitamin B1'],
            ['legacy_id' => 300, 'name' => 'Riboflavin - Vitamin B2'],
            ['legacy_id' => 301, 'name' => 'Niacin - Vitamin B3'],
            ['legacy_id' => 302, 'name' => 'Vitamin B6'],
            ['legacy_id' => 303, 'name' => 'Folic Acid'],
            ['legacy_id' => 304, 'name' => 'Vitamin B12'],
            ['legacy_id' => 305, 'name' => 'Biotin'],
            ['legacy_id' => 306, 'name' => 'Pantothenic Acid'],
            ['legacy_id' => 307, 'name' => 'Calcium'],
            ['legacy_id' => 308, 'name' => 'Zinc'],
            ['legacy_id' => 309, 'name' => 'Selenium'],
            ['legacy_id' => 310, 'name' => 'Chromium'],
            ['legacy_id' => 311, 'name' => 'Manganese'],
            ['legacy_id' => 312, 'name' => 'Molybdenum'],
            ['legacy_id' => 313, 'name' => 'Omega 3,6, & 9 Fatty Acid Blend'],
            ['legacy_id' => 314, 'name' => 'Natural Carotenoid Blend'],
            ['legacy_id' => 315, 'name' => 'Prebiotic Multi-Fiber Complex and Digestive Support'],
            ['legacy_id' => 316, 'name' => 'Super-Phyto Food Complex'],
            ['legacy_id' => 317, 'name' => 'Cardiovascular, Liver Cleanse, and Detox Support'],
            ['legacy_id' => 318, 'name' => 'Youth and Energy Complex'],
            ['legacy_id' => 319, 'name' => 'Vegetarian Amino Acid Complex (from Organic Quinoa)'],
            ['legacy_id' => 320, 'name' => 'Sea Vegetation Derived Ionic Trace Materials'],
            ['legacy_id' => 321, 'name' => 'Magnesium'],
            ['legacy_id' => 322, 'name' => 'Erythritol'],
            ['legacy_id' => 323, 'name' => 'Net Carbs Minus Fiber'],
            ['legacy_id' => 324, 'name' => 'Teafense'],
            ['legacy_id' => 325, 'name' => 'Baikal Skullcap (Root)'],
        ];

        foreach ($nutrients as $nutrient) {
            Nutrient::updateOrCreate(
                ['legacy_id' => $nutrient['legacy_id']],
                ['name' => $nutrient['name']]
            );
        }

        $this->command->info('Seeded ' . count($nutrients) . ' nutrients.');
    }
}
